# Utilizăm imaginea oficiala Oracle Database
FROM container-registry.oracle.com/database/enterprise:latest

# Definim variabilele de mediu
ENV ORACLE_SID=ORCL \
    ORACLE_PWD=oracle 

# Porturile pe care vrem să le expunem
EXPOSE 1521