export const FIREBASE_PATH = "cvs/"
export const CANDIDATE_ACCOUNT = "ROLE_CANDIDATE"
export const EMPLOYER_ACCOUNT = "ROLE_EMPLOYER"
export const ADMIN_ACCOUNT = "ROLE_ADMIN"
export const PRINCIPAL_ADMIN_EMAIL = "admin.joblistic@gmail.com"
export const PROCESSED = "procesat"
export const UNPROCESSED = "neprocesat"
export const CLOSED = "inchis"
export const OPENED = "deschis"

