version: '3'

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    networks:
      - platformnet
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - platformnet
      
networks:
  platformnet: